### ISSUE TITLE
Support a "me" alias.

### ISSUE THREAD

**Issue by castrojo** [juju-solutions/review-queue-classic#1]
The ability for people to do "reviewqueue_url/$name" is handy. Please support a +me directive like Launchpad does. (Or something similar)

That way we can tell people:

"Go to charmproof.com/+me to see where your charm is in the review process" and not have to have them URL hack or guess usernames or any of that.

**Comment by marcoceppi** [comment]
This is currently in the works, but will require login working or some clever cookie reading.

**Comment by marcoceppi** [comment]
This is now `/user/+me`
