### ISSUE TITLE
lp:~niedbalski/charms/precise/rabbitmq-server/trunk in queue but 404s

### ISSUE THREAD

**Issue by arosales** [juju-solutions/review-queue-classic#10]
This item is in the review queue, but the link goes no where. I am guessing the MP was deleted, however the review queue is still showing this item.

**Comment by arosales** [comment]
Same for https://code.launchpad.net/~tribaal/charms/precise/storage/add-unit-tests-target-to-makefile/+merge/231157

Still shows in the review queue, but does not have a valid MP. I think this is due to the MP being deleted, however it still shows in the review queue.

**Comment by marcoceppi** [comment]
These have been removed
