### ISSUE TITLE
Reviews in the queue no longer exist in Launchpad

### ISSUE THREAD

**Issue by AdamIsrael** [juju-solutions/review-queue-classic#25]
There's a number of reviews floating at the top of the queue that no longer exist in Launchpad. I've locked the ones I've come across to myself so other reviewers will skip over them.
- [lp:~brad-marshall/charms/precise/bip/add-amulet-tests](https://code.launchpad.net/~brad-marshall/charms/precise/bip/add-amulet-tests/+merge/241233)
- [lp:~brad-marshall/charms/trusty/mongodb/add-nrpe-checks](https://code.launchpad.net/~brad-marshall/charms/trusty/mongodb/add-nrpe-checks/+merge/241491)
- [lp:~mbruzek/charms/precise/assaultcube/tests](https://code.launchpad.net/~mbruzek/charms/precise/assaultcube/tests/+merge/240872)
- [lp:~heut2008/charms/trusty/rabbitmq-server/sync-charmhelpers](https://code.launchpad.net/~heut2008/charms/trusty/rabbitmq-server/sync-charmhelpers/+merge/238679)
- [lp:~larry-e-works/charms/trusty/nagios/nagios-added-template-config](https://code.launchpad.net/~larry-e-works/charms/trusty/nagios/nagios-added-template-config/+merge/242354)

**Comment by marcoceppi** [comment]
I've updated all of these manually in the queue. In the next release of the review queue I hope to address this but will also add an "Acknowledged" button which will remove it from the queue until the state of that review changes.
