### ISSUE TITLE
OpenStack Charm Queue

### ISSUE THREAD

**Issue by lazypower** [juju-solutions/review-queue-classic#32]
I know that multiple queues are on the roadmap. I was doing some brain bending around our handoff process, and it strikes me as a great way to handle this by just reading a tag off the launchpad bug to move an item from ECO/public charm queues to the respective review teams queue.

EG: Midonet as an  incoming charm was assigned to eco. They passed store review, and should now move to OpenStack rev process. Tagging the bug with "openstack" would be a great way to just shift this to the next phase.

**Comment by marcoceppi** [comment]
Any changes to the review queue which emphasis continued integration with
LaunchPad won't be considered. At this point it's simply work that's going
to be thrown away.
