### ISSUE TITLE
Advanced follow up logic

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/review-queue-classic#4]
We talked about an advanced way to handle bugs by non charmers.  If they set the state to Fix Released it will fall out of the queue.  The review queue could check to see if the user was not a charmer and set the state to "follow up"

if bug.state == fix_released && ! user.charmer:
  // Mark the bug as follow_up in the review queue.

**Comment by marcoceppi** [comment]
Duplicate of #2
