### ISSUE TITLE
No comments by bot in bugs for test results (ie Nginx/Hive/Tez/Storm)

### ISSUE THREAD

**Issue by arosales** [juju-solutions/review-queue-classic#9]
I am reviewing the Nginx charm and found the test to be "passing" per the review queue, but the bug was not commented on. The bug is:
https://bugs.launchpad.net/charms/+bug/1356856

Therefore I was not able to review the log. Other tests seem to be getting comments such as:
https://code.launchpad.net/~martin-hilton/charms/precise/gitlab/fixed-install-failure/+merge/234108

Thus, not sure why this particular one was note commented on.

-thanks,
Antonio

**Comment by arosales** [comment]
Also this particular bug is also showing up in the review queue even though the status is "Incomplete."

**Comment by arosales** [comment]
I am also seeing this for the Hive charm:
https://bugs.launchpad.net/charms/+bug/1356956

Review queue shows "fail" but not comment in the bug.

**Comment by arosales** [comment]
I am also seeing this in:
https://bugs.launchpad.net/charms/+bug/1366979
https://bugs.launchpad.net/charms/+bug/1360205

It seems bugs aren't being updated with the test result status.

**Comment by marcoceppi** [comment]
This is something wonky with launchpadlib not respecting me

**Comment by marcoceppi** [comment]
These have been resolved
